# WHAT IS PYTHON
Python is an interpreted, high-level language created by Guido van Rossum and released in 1991. It is dynamically typed.

Python programs have the extension .py and can be run from the command line by typing python file_name.py.

Python becomes the best solution in many domains from web applications, data analysis, data science, machine learning, and AI.

##### Common Feature Provided By python :

Simplicity: Think less of the syntax of the language and more of the code.

Open Source: A powerful language and it is free for everyone to use and alter as needed.

Portability: Python code can be shared and it would work the same way it was intended to. Seamless and hassle-free.

Being Embeddable & Extensible: Python can have snippets of other languages inside it to perform certain functions.

Being Interpreted: The worries of large memory tasks and other heavy CPU tasks are taken care of by Python, leaving you to worry only about coding.

Object Orientation: Objects help breaking-down complex real-life problems into such that they can be coded and solved to obtain solutions.

### Applications of Python.
    
Artificial Intelligence
    
Desktop Application

Automation

Web Development

Data Wrangling, Exploration And Visualisation.
    
#### Installation:
Download the latest version of Python for your operating system. 
In this case download Anaconda, then launch jupyter nb
So let's create our first Python program, Hello World program.

First, could you create a new folder where you will be saving you python files, let say Lux Academy?

Second, launch the VS code and open the new folder you created, Lux Academy.

Third, create a new python file, let say beginner.py file and enter the following code and save the file:

# Data Types
- Python has several built-in data types, which can be broadly categorized as follows:

#### Numeric Types:
int: Integer type, e.g., 3, 42, -7

float: Floating-point number (decimal), e.g., 3.14, -0.001

complex: Complex numbers with a real and imaginary part, e.g., 2 + 3j

#### Sequence Types:
   
str: String (sequence of characters), e.g., "Hello", 'Python'

list: Mutable ordered sequence of elements, e.g., [1, 2, 3], ["apple", "banana"]

tuple: Immutable ordered sequence of elements, e.g., (1, 2, 3), ("apple", "banana")

range: Represents a range of numbers, e.g., range(0, 10)Mapping Type:

dict: Dictionary, a collection of key-value pairs, e.g., {"name": "Alice", "age": 30}  

#### Set Types:
set: Unordered collection of unique elements, e.g., {1, 2, 3}, {"apple", "banana"}

Boolean Type:

bool: Represents True or False

#### Binary Types:
    
bytes: Immutable sequence of bytes, e.g., b'hello'

bytearray: Mutable sequence of bytes, e.g., bytearray(b'hello')

memoryview: A view object that exposes the internal data of an object that supports the buffer protocol, e.g., memoryview(b'hello')

### None Type:

NoneType: Represents the absence of value, e.g., None

### Callable Types:
function: A function is a block of code which only runs when it is called.

lambda: An anonymous, inline function defined using the lambda keyword.


# Variables
 - Variables are containers for storing data values could be numerical or textual
   
 - Variables are case sensitive
   
Rules of naming variables: 

 - you can't assign keywords(they form the core syntax and structure of the language.), or built-in functions(While you can assign built-in function names as variables, doing so will override the function, making it unavailable for future use. It's generally discouraged because it could lead to confusion and bugs in your code.)
 - variables cannot contain spaces to separate words use underscores
   

In [1]:
# Python Built-in Functions
print(dir(__builtins__))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BaseExceptionGroup', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EncodingWarning', 'EnvironmentError', 'Exception', 'ExceptionGroup', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'S

In [2]:
import keyword
print(keyword.kwlist)


['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [13]:
True = 'Python is a Programming Language'
print(True)

SyntaxError: cannot assign to True (1930483046.py, line 1)

In [14]:
x = 70
print(x)

70


In [3]:
type(x)

int

In [16]:
g = 'I am a Kenyan'
print(g)

I am a Kenyan


This flexibility allows Python variables to be reassigned with new values or types, but it's important to manage this carefully in more complex programs to avoid confusion or errors.

In [3]:
your_name = 'My name is Wangechi'
print(your_name)

My name is Wangechi


In [18]:
# camel case
myvariableName = 'John'
print(myvariableName) 

John


In [20]:

#Pascal case
MyVariableName = 'John'
print(MyVariableName) 

John


In [21]:
# SnakeCase
my_variable_name = 'John'
print(my_variable_name)

John


In [22]:
ice_cream = ['strawberry', 'vanilla','mango']
a,b,c = ice_cream
print(a)
print(b)
print(c)

strawberry
vanilla
mango


## Comments
Describes why a piece of code was written

when python interpreter executes the code, it ignores the comments

Comments start with #


In [25]:
# This is a single-line comment
x = 10 

### Numbers
Python supports:
integer - They thave type int

float- Any number with a decimal point is a floating number, has type float

complex numbers

# Data Types

In [8]:
type(12)


int

In [26]:
type(8.9)

float

In [9]:
type(10.01)

float

In [11]:
type(10+3j)

complex

In [9]:
type(790j)

complex

## Arithmetic Operators - Used to form expressions

Addition (+) 

Subtraction (-)

Multiplication (*)

Division (/)

Floor Division (//) - Divides two numbers and rounds the result down to the nearest whole number (integer division).

Modulus (%) - Returns the remainder after division

Exponential (**) Raises the first number to the power of the second number.

In [10]:
# Addition
a= 10
b = 5
result = a + b
print(result) 


15


In [11]:
# Subtraction
a = 10
b = 5
result = a - b
print(result) 


5


In [12]:
# Multiplication
a = 10
b = 5
result = a * b
print(result)  


50


In [14]:
# Floor Division
a = 16
b = 5
result = a // b
print(result)# Drops the remainder

3


In [18]:
# Modulus
a = 10
b = 4
result = a % b
print(result) 

2


In [27]:
a = 10
b = 4
result = a ** b
print(result) 

10000


# Boolean values
- Booleans represent one of two values: True or False.

In [33]:
type(5>3)

bool

In [14]:
bool(1>5)

False

In [15]:
bool(5>1)

True

In [ ]:
# ()- parenthesis
# [] - box brackets
# {} curly braces

# Strings
### Python strings are zero-indexed, meaning that the first character of the string has index 0, the second character has index 1, and so on.

In [34]:
j= 'single quote'
print(j)

single quote


In [35]:
type(j)

str

In [17]:
"Ann"

'Ann'

In [38]:
message = "it's a string"
print(message)

it's a string


In [37]:
# Indexing
a = 'My name is Monty!'
print(a[5])#does not include the 5

m


In [47]:
# Slicing: Specify the start index and the end index, separated by a colon, to return a part of the string.
print(a[5:]) # From 5 to the end

me is Monty!


In [48]:
print(a[:4])# Get the characters from the start to position 4 (not included):

My n


In [46]:
print(a[4:8])# start (inclusive): Start extracting from the character at index 4.
# end (exclusive): Stop extracting before the character at index 4.
# So, a[4:8] extracts characters starting at index 4 and ending before index 8


ame 


In [49]:
print(len(a))

17


## Multiline Strings
- You can assign a multiline string to a variable by using three quotes:

In [42]:
b = '''I love coding,
it makes me happy,
hell yeah I'm nerd'''
print(b)

I love coding,
it makes me happy,
hell yeah I'm nerd


In [1]:
#Example 3, escape characters:

escape_str = "She said: \"Python is great!\""
print(escape_str) # She said: "Python is great!"  


She said: "Python is great!"


In [2]:
# Example 4, concatenate strings:

one = "Lux"
two = "Academy"
print(one + " " + two) # Lux Academy 
## Note you can not concatenate strings with numbers

Lux Academy


In [3]:
# Example 5: interpolation.

# method 1
first_name = "Lux"
last_name = "Academy"
greet = f"Welcome at {first_name} {last_name}!" 
print(greet)  # Welcome at Lux Tech Academy!

Welcome at Lux Academy!


# lists

In [25]:
[1,2,3]

[1, 2, 3]

In [29]:
['Rice','cakes']

['Rice', 'cakes']

In [27]:
['rice',4,'oman']

['rice', 4, 'oman']

In [30]:
goods = ['Rice','cakes']
goods.append('chapati')
goods

['Rice', 'cakes', 'chapati']

In [32]:
goods[0] = 'porridge'#Changing the index
goods

['porridge', 'cakes', 'chapati']

In [35]:
type(goods)

list

### List Comprehension
- List comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list.

In [17]:
# Before :  write a for statement with a conditional test inside:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

['apple', 'banana', 'mango']


## newlist = [expression for item in iterable if condition == True]

In [18]:
# With list comprehension you can do all that with only one line of code
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [x for x in fruits if "a" in x]

print(newlist)

['apple', 'banana', 'mango']


In [19]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [x for x in fruits]# no conditions here

print(newlist)

['apple', 'banana', 'cherry', 'kiwi', 'mango']


# Tuples

- A tuple is almost similar with lists the only difference is that a tuple is immutable(cannot be modified or changed after it is created)

In [40]:
cakes = (1,2,4,6,8)

In [34]:
type(cakes)

tuple

In [41]:
cakes[2]

4

In [ ]:
# Join the tuples

In [35]:
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)

tuple3 = tuple1 + tuple2
print(tuple3)

('a', 'b', 'c', 1, 2, 3)


The only way you can change a tuple is first converting it to a list then change back to a tuple

In [45]:
x = ("apple", "banana", "cherry")
y = list(x)
y[1] = "kiwi"
x = tuple(y)

print(x)

('apple', 'kiwi', 'cherry')


# Indexing

In [29]:
this_tuple = ("apple", "banana", "cherry")
print(this_tuple[-1])# -1 means starting from the furthest right end

cherry


# Deleting

In [46]:
this_tuple = ("apple", "banana", "cherry")
del this_tuple 

In [47]:
print(this_tuple) # Error cause its already deleted

NameError: name 'this_tuple' is not defined

# Sets
- is a built-in data type that represents an unordered collection of unique elements.

- it cannot be accessed through index because it is unordered

- Mutable: Sets are mutable, meaning you can add or remove items after the set has bee

In [6]:
# Using curly braces
my_log = {1, 2, 3, 4}
print(my_log) 

{1, 2, 3, 4}


In [3]:
type(my_log)

set

In [48]:
# Using the set() function
another_set = set([1, 2, 3, 4, 4,7,6,6,6,89,40])  # Note: the duplicate '4' will be ignored
print(another_set) 

{1, 2, 3, 4, 6, 7, 40, 89}


In [4]:
another_set.update([5, 10, 20])  # Add multiple elements
print(another_set)  

{1, 2, 3, 4, 5, 6, 7, 40, 9, 10, 20, 89}


In [7]:

another_set.remove(2)  # Removes the element 2
print(another_set)  

{1, 3, 4, 5, 6, 7, 40, 9, 10, 20, 89}


# Dictionaries
 Key/value pair

In [49]:
dict_cake = {'name': 'Peter', 'daily intake': 5, 'favorite cake': ['Pauls', 'Chocolate']}

In [12]:
type(dict_cake)

dict

In [13]:
dict_cake.values()

dict_values(['Peter', 5, ['Pauls', 'Chocolate']])

In [14]:
dict_cake.keys()

dict_keys(['name', 'daily intake', 'favorite cake'])

In [10]:
dict_cake.items()

dict_items([('name', 'Peter'), ('daily intake', 5), ('favorite cake', ['Pauls', 'Chocolate'])])

In [16]:
dict_cake['name'] = 'Rose'
print(dict_cake)

{'name': 'Rose', 'daily intake': 5, 'favorite cake': ['Pauls', 'Chocolate']}


In [50]:
dict_cake.update({'name': 'Joan', 'daily intake': 10, 'favorite cake': ['Pauls', 'Chocolate'], 'weight':100 }) # update
print(dict_cake)

{'name': 'Joan', 'daily intake': 10, 'favorite cake': ['Pauls', 'Chocolate'], 'weight': 100}


In [12]:
del(dict_cake['daily intake'])
print(dict_cake)

{'name': 'Peter', 'favorite cake': ['Pauls', 'Chocolate'], 'weight': 89}


#  Comparison Operators

== Equal

!= Not Equal

> Greater than

>= greater than or equal to

< less than

<= Less than or equal to

In [52]:
10 ==70

False

In [18]:
10 != 40

True

In [19]:
'Chocolate' == 'Chocolate'

True

In [20]:
'Chocolate' == 'Vanilla'

False

In [26]:
40 >= 10

True

In [22]:
50 <= 10

False

In [56]:
a = 150
b = 36

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")

b is not greater than a


# LOGICAL OPERATORS
and = Returns True if both Statements are True

or = Returns True if one of the statements is True

not = Reverses the results and returns False if the result is True

In [12]:
(20>10) and (30>5)


True

In [14]:
(70>10) or (80>500) #one of the statement is true

True

In [15]:
not(20>10) and (30>5)


False

#### Membership Operators
in - Returns True if a sequence with the specified value is present in the object

not in - Returns True if a sequence with the specified value is not present in the object

In [19]:
fruits = ['apple', 'banana', 'cherry']
print('apple' in fruits)  

True


In [21]:
fruits = ['apple', 'banana', 'cherry']
print('orange' not in fruits)


True


## If Statements
- An "if statement" is written by using the if keyword.
  
 "if statement" checks the condition first
- if the condition evaluates to True, it executes the statement in the block otherwise ignore it
#### Colon (:) that follows the condition is very important

In [24]:
a = 33
b = 200
if b > a:
  print("b is greater than a")

b is greater than a


In [58]:
age= 23
if int(23) >= 18:
    print("You're Eligible to vote")
    

You're Eligible to vote


## Elif
- The elif keyword is Python's way of saying "if the previous conditions were not true, then try this condition".
- The code inside the else block will only execute if all previous conditions were False
- You can have as many elif statements as you want but you can only have one if and one else statement

In [59]:
a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

a and b are equal


### Else
- It acts as a catch-all for cases where none of the if or elif conditions are True.

In [32]:
a = 140
b = 36
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")
## In this example a is greater than b, so the first condition is not true, 
## also the elif condition is not true, so we go to the else condition and print to screen that "a is greater than b".

a is greater than b


## Loops
### For Loop
- A for loop in Python is used to iterate over a sequence (like a list, tuple, string, or range) and execute a block of code repeatedly for each element in the sequence. It is a common way to handle tasks like traversing through a list of items, performing repetitive operations, and mor

In [33]:
fruits = ["apple", "banana", "cherry"]

for fruit in fruits:
    print(fruit)


apple
banana
cherry


In [60]:
for i in range(9):# used in for loops when you need to iterate a certain number of times.
    print(i)


0
1
2
3
4
5
6
7
8


In [36]:
# foor loop
for x in range(0, 3):
  print(x)

0
1
2


In [61]:
# Break
fruits = ["apple", "banana", "cherry", 'kiwi']
for x in fruits:
  print(x) 
  if x == "banana":
    break # break: Exits the loop prematurely, stopping further iteration.

apple
banana


In [37]:
# Continue
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x) # With the continue statement we can stop the current iteration of the loop, and continue with the next:

apple
cherry


## While Loop
 
- A while loop in Python repeatedly executes a block of code as long as a given condition remains True. Unlike a for loop, which iterates over a sequence, a while loop runs based on a condition and continues until that condition becomes False.

In [38]:
i = 1
while i < 5:
  print(i)
  i += 1

1
2
3
4


####  A while loop will continue running indefinitely if the condition never becomes False. This can lead to an infinite loop, where the loop runs forever. You should ensure there’s a way for the condition to become False inside the loop using: Break


In [40]:
count = 0

while count < 10:
    if count == 7:
        break  # Exit the loop when count reaches 7
    print(count)
    count += 1


0
1
2
3
4
5
6


#### Continue-  skips the current iteration.

In [41]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue # Skip printing when count is 3
  print(i)

1
2
4
5
6


## Functions 
A function is a block of code which only runs when it is called.

You can pass data, known as parameters, into a function.A function is delimited with def res

### From a function's perspective:

A parameter is the variable listed inside the parentheses in the function defin(name)ition.

An  argua piece of data that you pass into the function.led.ult.

In [44]:
# without parameters
def greet(): # def: The keyword to define a function.
    print("Hello, welcome!")

greet()  # Call the function


Hello, welcome!


In [43]:
# Example 2 With parameters
def greet(name):
    print(f"Hello, {name}!")

greet("Lux")  # Call the function with an argument


Hello, Lux!


### Assignment : Go and check what *args and **kwargs are and how they are used:

## Lambda function
- syntax: lambda arguments : expression
- A lambda function is a small anonymous function that can have any number of arguments but only one expression.

In [46]:
square = lambda x: x ** 2
print(square(5)) 


25


In [62]:
x = lambda a, b : a ** b
print(x(5, 6))# multiple arguments

15625


### Class and Objects
- A class is a blueprint for creating objects. It defines a set of attributes (data) and methods (functions) that the objects created from the class can use
- The self Parameter
  
The self parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class.

It does not have to be named self , you can call it whatever you like, but it has to be the first parameter of any function in the class:

In [52]:
# Basic Syntax
class ClassName:
    def __init__(self, parameters):
        # Constructor: Initializes attributes
        self.attribute = parameters

    def method(self):
        # Method: Defines a behavior of the class
        pass

        
# class: The keyword used to define a class.
# __init__: A special method called a constructor that initializes the object’s attributes when an instance is created.
# self: A reference to the current instance of the class. It is used to access attributes and methods within the class.

In [54]:
class Dog:
    def __init__(self, name, age):
        self.name = name  # Attribute for dog's name
        self.age = age    # Attribute for dog's age

    def bark(self):  # Method for dog's bark behavior
        return f"{self.name} says Woof!"

# Creating an object (instance) of the Dog class
my_dog = Dog("Rio", 3)

# Accessing attributes and methods
print(my_dog.name)
print(my_dog.bark()) 


Rio
Rio says Woof!


#### An object is an instance of a class. When you create an object from a class, you can access the class’s attributes and methods.

Creating Objects:
You can create multiple objects from the same class, each with its own attributes.

In [56]:
dog1 = Dog("Rio", 3)
dog2 = Dog("Max", 5)

print(dog1.bark()) 
print(dog2.bark()) 


Rio says Woof!
Max says Woof!


## Inheritance
Inheritance allows a class (child class) to inherit attributes and methods from another class (parent class). It promotes code reusability.

Inheritance allows us to define a class that inherits all the methods and properties from another class.

Parent class is the class being inherited from, also called base class.

Child class is the class that inherits from another class, also called derived class.

In [62]:
# Parent class
class Animal:
    def __init__(self, name):  # Constructor method, initializes the object with a 'name' attribute
        self.name = name  # 'self.name' is an instance attribute, set to the value of the 'name' parameter

    def speak(self):  # A method in the parent class that will be overridden by child classes
        return "Some generic sound"  # Returns a generic sound for any generic animal

# Child class that inherits from the Animal class
class Dog(Animal):  # 'Dog' class inherits from 'Animal', meaning it has access to its attributes and methods
    def speak(self):  # Overrides the 'speak()' method from the Animal class
        return "Woof!"  # Returns "Woof!" when called, specific to dogs

# Another child class that inherits from the Animal class
class Cat(Animal):  # 'Cat' class also inherits from 'Animal'
    def speak(self):  # Overrides the 'speak()' method from the Animal class
        return "Meow!"  # Returns "Meow!" when called, specific to cats

# Creating objects of Dog and Cat classes
dog = Dog("Buddy")  # Creating an instance of the Dog class with the name 'Buddy'. The __init__ method from Animal is called here.
cat = Cat("Whiskers")  # Creating an instance of the Cat class with the name 'Whiskers'. The __init__ method from Animal is called.

# Calling methods
print(dog.name)    # Accesses the 'name' attribute of the dog object, prints: Buddy
print(dog.speak()) # Calls the 'speak()' method of the dog object, prints: Woof!
print(cat.name)    # Accesses the 'name' attribute of the cat object, prints: Whiskers
print(cat.speak()) # Calls the 'speak()' method of the cat object, prints: Meow!


Buddy
Woof!
Whiskers
Meow!


## Numpy
- NumPy (Numerical Python) is a powerful library in Python that is essential for data analysis, especially when dealing with large datasets and numerical computations. It provides support for arrays, matrices, and many mathematical functions that operate on these data structures. Here's an overview of NumPy, tailored for you as a data analyst:

- Installation: pip install numpy

- Importation: import numpy an np

- The core feature of NumPy is its powerful N-dimensional array object, called ndarray. This allows you to work with multi-dimensional data efficiently

In [63]:
!pip install numpy

In [64]:
import numpy as np

In [65]:
# 1D array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)

# 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", array_3d)


1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### NumPy allows you to perform element-wise operations on arrays without the need for explicit loops.

In [26]:
a = np.array([10, 40, 30])
b = np.array([1, 2, 3])

# Addition
print("Addition:", a + b)  

# Multiplication
print("Multiplication:", a * b) 


Addition: [11 42 33]
Multiplication: [10 80 90]


#### NumPy provides a wide array of mathematical functions, making it easy to perform complex calculations.

In [68]:
data = np.array([1, 2, 3, 4, 5, 6 , 2, 8])
# Mean
np.mean(data) 


3.875

In [40]:
# Median
np.median(data)

3.5

In [42]:
from scipy import stats

mode_result = stats.mode(data)
mode_result.mode

2

In [69]:
# Standard Deviation
np.std(data)

2.2043990110685496

#### Indexing and slicing

In [47]:
array = np.array([10, 20, 30, 40, 50])
# Accessing elements
array[0]

10

In [48]:
array[1:4]

array([20, 30, 40])

### Reshaping Arrays
 You can change the shape of an array without changing its data.

In [49]:
array = np.array([[1, 2, 3], [4, 5, 6]]) #This one has 2rows, 3 columns
reshaped_array = array.reshape(3, 2)
reshaped_array

array([[1, 2],
       [3, 4],
       [5, 6]])

#### NumPy is the foundation for many other data analysis libraries, such as Pandas, Matplotlib, and SciPy.

- Pandas: For data manipulation and analysis.
  
- Matplotlib: For data visualization.
  
- SciPy: For scientific computing.